### ISSUE TITLE
404

### ISSUE THREAD

**Issue by zzy-design** [Rock-Candy-Tea/hexo-circle-of-friends#105]
接口是通的 有返回数据，但是登陆不了，朋友圈页面也刷新不了 404错误 
附地址：http://codey.cc/fcircle/
接口地址：https://s.codey.cc/all
![image](https://github.com/Rock-Candy-Tea/hexo-circle-of-friends/assets/69064727/c0ec679a-aaf1-4aa3-8b13-9884df1b9b9d)
![image](https://github.com/Rock-Candy-Tea/hexo-circle-of-friends/assets/69064727/26480143-52a1-44ed-9536-f0a58a2088b4)

**Comment by hiltay** [comment]
请求路径错了，不是`/all/login`而应该是`/login`

**Comment by zzy-design** [comment]
已解决，多谢

**Comment by zzy-design** [comment]
> 请求路径错了，不是`/all/login`而应该是`/login`

已解决，多谢
