### ISSUE TITLE
github部署失败

### ISSUE THREAD

**Issue by ning0818** [Rock-Candy-Tea/hexo-circle-of-friends#106]
https://github.com/ning0818/hexo-circle-of-friends/actions/runs/5229134666/jobs/9441942115

**Comment by ning0818** [comment]
![image](https://github.com/Rock-Candy-Tea/hexo-circle-of-friends/assets/117955401/7e2b4bf7-76d2-449f-9fc5-d8e3ad10e854)

**Comment by hiltay** [comment]
配置文件yaml格式有问题

**Comment by ning0818** [comment]
> 配置文件yaml格式有问题

麻烦可以帮忙看下哪里的格式不对吗？
https://github.com/ning0818/hexo-circle-of-friends/blob/main/hexo_circle_of_friends/fc_settings.yaml
https://github.com/ning0818/hexo-circle-of-friends/blob/main/.github/workflows/main.yml

**Comment by hiltay** [comment]
错误日志里写得很清楚。

**Comment by ning0818** [comment]
> 错误日志里写得很清楚。

?
![image](https://github.com/Rock-Candy-Tea/hexo-circle-of-friends/assets/117955401/2dc986b5-7bbb-4eee-a1d2-b06a6bfd6a03)

**Comment by ning0818** [comment]
请问在哪里写了？
!()[https://user-images.githubusercontent.com/117955401/246642077-2dc986b5-7bbb-4eee-a1d2-b06a6bfd6a03.png]

**Comment by hiltay** [comment]
注意看error log，`fc_settings.yaml`文件中的第32行导致。`LINK`字段前不应该有空格。
