### ISSUE TITLE
关于Yun主题的小问题

### ISSUE THREAD

**Issue by TNXG** [Rock-Candy-Tea/hexo-circle-of-friends#20]
是不是不支持Yun主题的“随机友链(外置的 JSON 加载方式)”啊（doge）

**Comment by hiltay** [comment]
外置JSON加载之后，只要在`/link`页面下能显示友链列表就支持。
比如https://www.yunyoujun.cn/links/

**Comment by TNXG** [comment]
> 外置JSON加载之后，只要在页面下能显示友链列表就支持。 比如 https://www.yunyoujun.cn/links/`/link`

2022-01-30 07:03:12 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/twisted/internet/defer.py", line 1661, in _inlineCallbacks
    result = current_context.run(gen.send, result)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/scrapy/crawler.py", line 89, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
IndexError: list index out of range
Error: Process completed with exit code 1.
那Yun主题的这种情况怎么解决（卑微）

**Comment by hiltay** [comment]
大概看了下Yun源码，采用JSON之后引入是异步的，原来的请求确实获取不到了。
如果要开启的话，在`settings.py`里手动配置友链吧

**Comment by TNXG** [comment]
> 大概看了下Yun源码，采用JSON之后引入是异步的，原来的请求确实获取不到了。 如果要开启的话，在`settings.py`里手动配置友链吧

了解，希望后续版本迭代可以适配

**Comment by hiltay** [comment]
> > 大概看了下Yun源码，采用JSON之后引入是异步的，原来的请求确实获取不到了。 如果要开启的话，在`settings.py`里手动配置友链吧
> 
> 了解，希望后续版本迭代可以适配

会在近期更新中解决。

**Comment by hiltay** [comment]
已更新。
