### ISSUE TITLE
[Suggestion]排序

### ISSUE THREAD

**Issue by YiHui-Liu** [Rock-Candy-Tea/hexo-circle-of-friends#21]
现在前端、后端都有排序的部分，可以考虑在后端完成排序送回，前端在fetch的时候送入链接？

**Comment by 2X-ercha** [comment]
昨天刚更新的api，今天就来了issue，这波属于未仆先知（）

用最新的api，请求带上参数rule=updated或rule=created就行，如xxx.vercel.app/api?rule=created

如无疑问，这条issue将被关闭

**Comment by YiHui-Liu** [comment]
✌🆗前端的js代码也需要更新
