### ISSUE TITLE
randomfriend接口提供友链数量参数

### ISSUE THREAD

**Issue by zhheo** [Rock-Candy-Tea/hexo-circle-of-friends#29]
支持生成要求数量的友链，方便添加多个友链到页脚

**Comment by hiltay** [comment]
在[branch-dev](https://github.com/Rock-Candy-Tea/hexo-circle-of-friends/tree/dev)初步完成了该功能，待测试后，将跟随新版本发布。

**Comment by hiltay** [comment]
4.3.2版本已添加
