### ISSUE TITLE
公共库源更新提醒

### ISSUE THREAD

**Issue by yzqzss** [Rock-Candy-Tea/hexo-circle-of-friends#31]
您好，我是 https://github.com/saveweb/rss-list 的维护者，看到这个项目用到了 saveweb/rss-list 作为公共库。

上一版本的 OPML 中有部分博客已经变成垃圾站了，垃圾站的RSS一直在发广告文章。

>比如『青山绿水』和『纬八路生活随笔集』，一直在发送垃圾文章。：![图片](https://user-images.githubusercontent.com/30341059/160623237-2994f6b8-0e25-4f4a-a562-59902aa7d7fa.png)

我们新版的 OPML 还没有发布，建议先使用 https://box.othing.xyz/realtime.opml.xml 的 OPML 替换目前公共库使用的 OPML 。

正式的新版 OPML 将于近期发布，谢谢。

另外，你们项目有交流群之类的吗？如果有的话，我想加入一下。:P

**Comment by 2X-ercha** [comment]
感谢反馈，公共库源其实一直还没有上线使用，但我们在测试的同时也发现了很大一部分的链接失效现象（数量大概在120个左右）
请加我qq：2274362243，我再邀请到开发群
