### ISSUE TITLE
改错仓库了

### ISSUE THREAD

**Issue by Falling42** [Rock-Candy-Tea/hexo-circle-of-friends#35]
![image](https://user-images.githubusercontent.com/90437129/162383849-95cbd613-f72a-4568-9fed-1523430fceeb.png)
我想改我自己fork的仓库 然后我点错了
![image](https://user-images.githubusercontent.com/90437129/162383938-3a1facd4-709c-4242-b544-49826469cedc.png)
但是我不知道为什么这个仓库在我这里显示
抱歉

**Comment by yzqzss** [comment]
Recent Repos 会显示你最近浏览的仓库。并不是“意外”，这是 Github 的一个正常功能……
你自己的 Recent Repos 只会对你显示。
