### ISSUE TITLE
[bug] 文章与作者不匹配

### ISSUE THREAD

**Issue by 2X-ercha** [Rock-Candy-Tea/hexo-circle-of-friends#36]
（来自群友反馈）仓库地址：https://github.com/Ser-MingShao/hexo-circle-of-friends

![图片](https://user-images.githubusercontent.com/72645310/162733491-1f52d558-5ef1-40aa-8468-f2c0c9d9123e.png)

红框的是店长的文章

**Comment by Ser-MingShao** [comment]
名字是我博客名字SerMs.爬到得是店长得文章

**Comment by 2X-ercha** [comment]
（注：不是个例）
