### ISSUE TITLE
当点击活跃后，界面将无法在加载

### ISSUE THREAD

**Issue by LanYunDev** [Rock-Candy-Tea/hexo-circle-of-friends#39]
当点击活跃后，界面将无法在加载。试图修复但依然失败，排除过一些问题，但仍然未解决。
百分百复现。
博客对应链接🔗：https://lanyundev.vercel.app/fcircle/
仓库相应链接🔗：https://github.com/LanYunDev/hexo-circle-of-friends
API：https://hexo-circle-of-friends-five.vercel.app/
<img width="766" alt="image" src="https://user-images.githubusercontent.com/95263282/168466134-2244f6ee-3aea-40ef-b7ac-7e8d34f45039.png">

<img width="144" alt="image" src="https://user-images.githubusercontent.com/95263282/168466089-18b3935e-aea7-4ac4-8490-1487587f5f31.png">
➜  Blog-博客 git:(main) ✗ hexo version
INFO  Validating config
INFO
  ===================================================================

      #####  #    # ##### ##### ###### #####  ###### #      #   #
      #    # #    #   #     #   #      #    # #      #       # #
      #####  #    #   #     #   #####  #    # #####  #        #
      #    # #    #   #     #   #      #####  #      #        #
      #    # #    #   #     #   #      #   #  #      #        #
      #####   ####    #     #   ###### #    # #      ######   #

                            4.2.1
  ===================================================================
hexo: 6.2.0
hexo-cli: 4.3.0
os: darwin 21.4.0 12.3.1

node: 18.0.0
v8: 10.1.124.8-node.13
uv: 1.44.1
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 108
nghttp2: 1.47.0
napi: 8
llhttp: 6.0.4
openssl: 1.1.1n
cldr: 40.0
icu: 70.1
tz: 2021a3
unicode: 14.0

**Comment by 2X-ercha** [comment]
![图片](https://user-images.githubusercontent.com/72645310/168466979-87d26470-df01-4b68-b8b2-943151aaa8af.png)
试试把套的这一层去掉？

**Comment by LanYunDev** [comment]
去掉保存，在无痕状态下预览，依然出现消失的问题。

**Comment by LanYunDev** [comment]
如图所示
<img width="866" alt="image" src="https://user-images.githubusercontent.com/95263282/168710756-d32d3e32-83b8-4bf5-b020-109ca090f0e6.png">
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/95263282/168710827-934fee6f-8174-4d38-9df8-11e98aa8fa3f.png">

**Comment by 2X-ercha** [comment]
很奇怪，你的活跃点完之后请求的链接有问题
![图片](https://user-images.githubusercontent.com/72645310/168717095-bd9942f4-d941-466f-bb91-480f454ddc4b.png)
我在本地并没有复现出这种情况。不知道是不是有其它的插件冲突到了？

**Comment by LanYunDev** [comment]
啊,应该没有冲突吧,这种情况应该会被复现叭...
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/95263282/168718866-437674f8-2e52-4343-85b3-eee380471dcf.png">

**Comment by 2X-ercha** [comment]
我没说明清楚，抱歉

用我自己的站点用你的api，本地无痕测试的：
![图片](https://user-images.githubusercontent.com/72645310/168727554-969d911e-b594-41ca-85dd-5dc192a3a749.png)
![图片](https://user-images.githubusercontent.com/72645310/168727524-4e41dbb6-d394-486c-b04d-1e415f67b13f.png)
![图片](https://user-images.githubusercontent.com/72645310/168727414-fcb647e4-e174-4c17-a289-789193ff5b1c.png)

在你的站点就会出这个问题。我不确定是不是因为你的站点里一些额外的链接替换之类的js导致了这个情况，本来应该请求公共库的内容`https://fcircle-pub.rct.cool/`被替换成了`https://lanyundev.vercel.app/fcircle/undefined`。

**Comment by LanYunDev** [comment]
是否因为这个的原因呢?https://lanyundev.vercel.app/js/custom/ServiceWorker.js
我感觉不太像是这个原因,我也没有替换链接替换之类的js,除了上面👆这个.

**Comment by 2X-ercha** [comment]
（感觉也不像sw的问题。匹配拦截也不会吞了原链接

**Comment by LanYunDev** [comment]
是的，刚刚排查了一下，不是sw的问题，我发现本地的话，链接也会被替换

**Comment by 2X-ercha** [comment]
等木木什么时候有空再来排查了

**Comment by LanYunDev** [comment]
好的，谢谢了...❤️

**Comment by lmm214** [comment]
vercel 

> 我没说明清楚，抱歉
> 
> 用我自己的站点用你的api，本地无痕测试的： ![图片](https://user-images.githubusercontent.com/72645310/168727554-969d911e-b594-41ca-85dd-5dc192a3a749.png) ![图片](https://user-images.githubusercontent.com/72645310/168727524-4e41dbb6-d394-486c-b04d-1e415f67b13f.png) ![图片](https://user-images.githubusercontent.com/72645310/168727414-fcb647e4-e174-4c17-a289-789193ff5b1c.png)
> 
> 在你的站点就会出这个问题。我不确定是不是因为你的站点里一些额外的链接替换之类的js导致了这个情况，本来应该请求公共库的内容`https://fcircle-pub.rct.cool/`被替换成了`https://lanyundev.vercel.app/fcircle/undefined`。

排除同上

**Comment by LanYunDev** [comment]
应该可以排除域名的问题,具体啥问题不太清楚...
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/95263282/179386048-0680d318-0909-4b37-9298-3b621a55889f.png">
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/95263282/179386082-03a6fc62-1bff-4ac1-a264-d02c777e164b.png">

**Comment by hiltay** [comment]
尝试5.x最新版部署
