### ISSUE TITLE
请求里 end = 20 时返回错误

### ISSUE THREAD

**Issue by jasonchio-cn** [Rock-Candy-Tea/hexo-circle-of-friends#41]
![image](https://user-images.githubusercontent.com/36125147/169637066-228a33fc-b0fa-4239-8b75-154727d6b618.png)

如果 end = 10，返回的数据时正常的
![image](https://user-images.githubusercontent.com/36125147/169637088-778c5647-af22-4c3d-8319-de877001bde1.png)

因为总共的文章就 11 篇，所以会有这个 bug。

**Comment by hiltay** [comment]
使用的部署方式？以及数据库能否提供一下

**Comment by hiltay** [comment]
在#52 中也出现了该问题，经过确认在当前版本存在此bug

后续会进行修复，感谢反馈！

**Comment by hiltay** [comment]
4.3.3已修复
