### ISSUE TITLE
跨域请求被屏蔽

### ISSUE THREAD

**Issue by i-abc** [Rock-Candy-Tea/hexo-circle-of-friends#45]
使用的是Chrome电脑版，一开始正常，过段时间后出现了跨域请求被屏蔽（期间未更改任何配置）；接着尝试用Edge电脑版、Chrome手机版，一切正常。
![Snipaste_2022-06-12_00-14-19](https://user-images.githubusercontent.com/104631897/173196059-0a8b98eb-c55b-43e8-9d76-34373643e642.png)

**Comment by 2X-ercha** [comment]
能不能给个站点地址呢，从截图只能看到链接/allall错误了

还有配置参数截图

**Comment by i-abc** [comment]
是我弄错了。

开始配置里api是[https://hexo-circle-of-friends-chi.vercel.app/](https://hexo-circle-of-friends-chi.vercel.app/)，也没问题，正常；
但后来不知道为什么我把api改成了[https://hexo-circle-of-friends-chi.vercel.app/all](https://hexo-circle-of-friends-chi.vercel.app/all)；
再后来我又把api改回了[https://hexo-circle-of-friends-chi.vercel.app/](https://hexo-circle-of-friends-chi.vercel.app/)，但浏览器缓存的数据还是[https://hexo-circle-of-friends-chi.vercel.app/all](https://hexo-circle-of-friends-chi.vercel.app/all)，就出现了上图那情况；
我刚才把浏览器数据全清了，正常了。

抱歉抱歉，确实改过配置了，结果忘了，大晚上的打扰了，麻烦了，真不好意思啊😥
