### ISSUE TITLE
抓取错位

### ISSUE THREAD

**Issue by BowenYoung** [Rock-Candy-Tea/hexo-circle-of-friends#47]
使用volantis策略抓取友链页面，将第一个友链的简介误判成了第二个友链的作者。示例站点：https://bowenyoung.cn/fcircle

**Comment by hiltay** [comment]
如果抓取错位，应该是某个友链解析错误，可以考虑换一种添加友链信息的方式，如配置项友链、json友链等

后续版本会尝试优化这部分的成功率

**Comment by BowenYoung** [comment]
感谢！暂时先用配置项替代！

**Comment by hiltay** [comment]
5.0.2已针对volantis抓取错位问题进行修复，更新版本尝试~

**Comment by BowenYoung** [comment]
> 5.0.2已针对volantis抓取错位问题进行修复，更新版本尝试~

已更新，bug解决！
