### ISSUE TITLE
Vercel 部署失败

### ISSUE THREAD

**Issue by Cystee** [Rock-Candy-Tea/hexo-circle-of-friends#54]
老版本部署是成功了的。现在更新了，我把原来的仓库删了重新来过，结果 Vercel 返回云函数错误 HTTP 500：

![image](https://user-images.githubusercontent.com/61391190/176989494-a978bc01-c347-452c-8109-84656777c9f7.png)

其他的正常，Leancloud 有 `friend_list` 和 `friend_poor`，Github Action 部署成功。仓库地址：

https://github.com/Cystee/hexo-circle-of-friends

**Comment by Cystee** [comment]
降级 4.3.2 部署成功。

**Comment by hiltay** [comment]
收到，已修复。感谢反馈。

**Comment by Cystee** [comment]
谢谢，已经好了
