### ISSUE TITLE
页面显示不正常

### ISSUE THREAD

**Issue by iwyang** [Rock-Candy-Tea/hexo-circle-of-friends#56]
打开是这样子，感觉错位了，出现了`avatar`字样：

![OTJio.png](https://s1.328888.xyz/2022/08/02/OTJio.png)

点击`Created`又正常了：

![OTy3F.png](https://s1.328888.xyz/2022/08/02/OTy3F.png)

不过只要一刷新就又错位了。

还有一个问题就是博客卡片不能显示博客名称，而是显示`undefined`

![OTXJB.png](https://s1.328888.xyz/2022/08/02/OTXJB.png)

仓库地址：https://github.com/iwyang/hexo-circle-of-friends

**Comment by hiltay** [comment]
@lmm214

**Comment by hiltay** [comment]
尝试改用5.0新版前端

**Comment by Cystee** [comment]
> 尝试改用5.0新版前端

经测试，刷新页面就会出现这种问题，新版也如此

**Comment by hiltay** [comment]
![image](https://user-images.githubusercontent.com/41409512/195150260-cbd54698-0ae2-45d7-993b-61894a7da80d.png)
不确定是不是渲染冲突..这个div似乎不属于朋友圈前端代码

**Comment by hiltay** [comment]
本来应该是一个`img`，在这里却变成了`a`和`div`

**Comment by hiltay** [comment]
确认是灯箱渲染的问题，尝试使用最新前端：https://fcircle-doc.yyyzyyyz.cn/#/frontenddeploy?id=%e6%96%b9%e6%a1%88%ef%bc%9ayyyz

**Comment by Cystee** [comment]
还是有同样的问题，测试页面：https://www.casecori.top/circle/

**Comment by hiltay** [comment]
> 还是有同样的问题，测试页面：https://www.casecori.top/circle/

刷新缓存后再看看，我这里已经好了

**Comment by Cystee** [comment]
> > 还是有同样的问题，测试页面：https://www.casecori.top/circle/
> 
> 刷新缓存后再看看，我这里已经好了

用无痕模式访问，进入页面再刷新后会出现这个问题

**Comment by hiltay** [comment]
```css
.img-alt.is-center {
    display: none;
}
```
那就只能暴力解决了，加上这个css吧

**Comment by Cystee** [comment]
有效 :-D
