### ISSUE TITLE
请求被拦截.

### ISSUE THREAD

**Issue by LanYunDev** [Rock-Candy-Tea/hexo-circle-of-friends#57]
CloudFlare拦截了请求,方法被识别为UNKNOWN
run.py请求优化一下应该能解决这个问题.现在是识别为自动攻击了.
WAP已将这个URL路径设置为允许了
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/95263282/183001736-52c7d1da-00fa-4746-9b3a-13a8d20a22ff.png">

<img width="976" alt="image" src="https://user-images.githubusercontent.com/95263282/183001471-b61512b7-184a-4f4d-9c4f-2ef934bb50cc.png">
<img width="1318" alt="image" src="https://user-images.githubusercontent.com/95263282/183001515-0c8e09bd-0fb6-4448-aa3c-3125d530a224.png">

**Comment by hiltay** [comment]
cf这个拦截机制不太清楚，等后续研究一下:(

**Comment by LanYunDev** [comment]
好滴~谢谢大佬回复~

**Comment by hiltay** [comment]
nonono是我太菜了(
