### ISSUE TITLE
文章重复

### ISSUE THREAD

**Issue by Cystee** [Rock-Candy-Tea/hexo-circle-of-friends#58]
运行一段时间就会出现问题，发布时间稍微早点的文章会重复。

![Screenshot_2022-08-14-22-34-34-728_com android chrome](https://user-images.githubusercontent.com/61391190/184541884-310bbdc4-f3d2-4393-8352-60a0e5036a2f.png)

采用 Leancloud 部署。

博客链接：https://www.casecori.top/circle/
仓库链接：https://github.com/Cystee/hexo-circle-of-friends
API：https://circori.vercel.app/all

**Comment by hiltay** [comment]
切换数据库之后还有问题吗

**Comment by Cystee** [comment]
还有问题：

![Screenshot_2022-10-12-17-49-00-054_com android chrome](https://user-images.githubusercontent.com/61391190/195312326-5c56116a-1a17-4015-8bcc-af3d55aedbc1.jpg)

而且点这篇文章的卡片会提示无法获取，只有点最新的那一个才能看到，卡片里只有一篇文章：

![Screenshot_2022-10-12-17-52-00-105_com android chrome](https://user-images.githubusercontent.com/61391190/195313840-b72b16ef-1676-4f73-b0e8-b18b32580c5a.jpg)

**Comment by hiltay** [comment]
这不是文章重复的问题
文章卡片获取不到说明数据库friend未查询到该作者，按照提示检查数据库，后续会考虑对无法获取的情况进行优化
如无其他问题，此issue将被关闭

**Comment by Cystee** [comment]
okok
