### ISSUE TITLE
樱花

### ISSUE THREAD

**Issue by brqs** [Rock-Candy-Tea/hexo-circle-of-friends#6]
[sakura](https://github.com/brqs/hexo-circle-of-friends/blob/dev/theme/sakura/sakura.py)
樱花主题分包，友链规则可以正常使用，主页规则有点问题，我怀疑是获取文章发布时间的字符串需要截取，但咱也不会截啊，等冰老师来看看怎么搞。

**Comment by DeSireFire** [comment]
这几天面试，可能没那么快更新。
你先把这几个码上，之后我看看怎么解决。
描述一下是出了什么问题？
是有什么样的需求？
提供一下能够能浮现该问题的博客链接，方便开发调试。

**Comment by 2X-ercha** [comment]
@brqs 

Sakura主题已经适配。由于1.17时本项目目录结构及主函数重构，建议重新fork本仓库。

如果没有其他问题，此条issue将被关闭。

**Comment by 2X-ercha** [comment]
hexo的樱花主题两种时间格式都已解决，非hexo的版本不作考虑。如有问题，建议留言
