### ISSUE TITLE
vercel+github+mongodb的部署方式获取随机文章的接口问题

### ISSUE THREAD

**Issue by flow2000** [Rock-Candy-Tea/hexo-circle-of-friends#60]
![image](https://user-images.githubusercontent.com/67251012/190451805-d913d9bf-87a9-4f66-aab8-e6dbd8ca39c0.png)
部署方式：GitHub+vercel+leancloud
https://friends.guole.fun/post

![image](https://user-images.githubusercontent.com/67251012/190452156-e0a6b79f-4234-40cf-a6e1-23727057d979.png)
部署方式：github+vercel+mongodb
https://fcircle.panghai.top/post

这两种部署方式中，使用一样的接口，返回的statistical_data数据不一致

**Comment by hiltay** [comment]
收到，这两个返回值确实不一样，下个版本会修复

**Comment by hiltay** [comment]
5.0.0 已经统一为`name`
