### ISSUE TITLE
请求适配主题

### ISSUE THREAD

**Issue by TNXG** [Rock-Candy-Tea/hexo-circle-of-friends#63]
框架名称：[Hexo](https://hexo.io/)
主题名称：[Miracle](https://github.com/oCoke/hexo-theme-miracle)
事例站点：[https://blog.tnxg.top/links/](https://blog.tnxg.top/links/)
显示方法：外部链接引入后渲染[/assets/data/links.json](https://blog.tnxg.top/assets/data/links.json)

**Comment by hiltay** [comment]
json方式是较为通用的方式；
后续看有没有时间和精力添加适配

**Comment by klsdfjo** [comment]
我是wordpress，可以用在wordpress吗
