### ISSUE TITLE
前台控制面板错位严重，且设置项无法保存！

### ISSUE THREAD

**Issue by penndu** [Rock-Candy-Tea/hexo-circle-of-friends#65]
呈现页面：https://dusays.com/fcircle/
问题截图：
![image](https://user-images.githubusercontent.com/46226528/194748845-6b7dc982-e3ea-4f50-a6f9-1f94a11cab30.png)
![image](https://user-images.githubusercontent.com/46226528/194748851-d2fd5dc7-283b-4dee-820d-fff380d4b483.png)

**Comment by hiltay** [comment]
更新了一版，增加了移动端的适配

**Comment by hiltay** [comment]
对volantis的适配确实有些问题，挂载的容器被限制在了page内...

**Comment by hiltay** [comment]
@anzhiyu-c

**Comment by hiltay** [comment]
已在[文档中](https://fcircle-doc.yyyzyyyz.cn/#/problems?id=_5x%e5%89%8d%e7%ab%af%e5%9c%a8volantis%e4%b8%bb%e9%a2%98%e6%98%be%e7%a4%ba%e7%9a%84%e9%97%ae%e9%a2%98)进行说明

**Comment by penndu** [comment]
> 已在[文档中](https://fcircle-doc.yyyzyyyz.cn/#/problems?id=_5x%e5%89%8d%e7%ab%af%e5%9c%a8volantis%e4%b8%bb%e9%a2%98%e6%98%be%e7%a4%ba%e7%9a%84%e9%97%ae%e9%a2%98)进行说明

1. 文档出现错误，<style>结尾处应是</style>；
2. src是不是应该去掉`/browse`字段；
3. 经测试可使用elemecdn节点加速，参考链接
```
<script type="text/javascript" src="https://npm.elemecdn.com/imgscdn@1.1.33/fcircle/app.min.js"></script>
<script type="text/javascript" src="https://npm.elemecdn.com/imgscdn@1.1.33/fcircle/bundle.js"></script>
```

**Comment by penndu** [comment]
![image](https://user-images.githubusercontent.com/46226528/194844347-13d60dff-c7e3-4429-ac43-e854f9cabc4c.png)
输入框旁的提示看不清。

**Comment by penndu** [comment]
![image](https://user-images.githubusercontent.com/46226528/194844468-08602b24-ab34-493a-98cf-1854e057e7aa.png)
无法正常保存。

**Comment by hiltay** [comment]
> ![image](https://user-images.githubusercontent.com/46226528/194844468-08602b24-ab34-493a-98cf-1854e057e7aa.png) 无法正常保存。

能否提供api日志，和前端错误信息

**Comment by hiltay** [comment]
> > 已在[文档中](https://fcircle-doc.yyyzyyyz.cn/#/problems?id=_5x%e5%89%8d%e7%ab%af%e5%9c%a8volantis%e4%b8%bb%e9%a2%98%e6%98%be%e7%a4%ba%e7%9a%84%e9%97%ae%e9%a2%98)进行说明
> 
> 1. 文档出现错误，<style>结尾处应是</style>；
> 2. src是不是应该去掉`/browse`字段；
> 3. 经测试可使用elemecdn节点加速，参考链接
> 
> ```
> <script type="text/javascript" src="https://npm.elemecdn.com/imgscdn@1.1.33/fcircle/app.min.js"></script>
> <script type="text/javascript" src="https://npm.elemecdn.com/imgscdn@1.1.33/fcircle/bundle.js"></script>
> ```

感谢勘误

**Comment by penndu** [comment]
按照文档重新部署后可正常使用，关闭议题~

**Comment by hiltay** [comment]
> 按照文档重新部署后可正常使用，关闭议题~

如果是github+sqlite，建议更新到最新版！
