### ISSUE TITLE
LeanCloud部署可能存在问题？

### ISSUE THREAD

**Issue by GC-ZF** [Rock-Candy-Tea/hexo-circle-of-friends#68]
因为以前一直习惯使用LeanCloud，查看文档发现5.x更新挺多的，所以删库重新操作，根据文档添加
github的环境变量
![image](https://user-images.githubusercontent.com/94956933/196945078-167e6509-53ac-470e-b930-96b243a37ae1.png)

vercel的环境变量
![image](https://user-images.githubusercontent.com/94956933/196945109-ab93a2a4-3d5d-4bfe-b2f6-8bd4a2291808.png)

工作流运行正常 https://github.com/GC-ZF/hexo-circle-of-friends/actions/runs/3289482837 
但是LeanCloud中并没有新建friend_list和friend_poor
这个时候我以为是ID和Key填错了，又删库重复操作了两遍结果还是相同
所以修改为了sqlite，在前端面板又尝试修改数据库管理方式，填写ID和Key之后又好了？所以我又删了LeanCloud的应用重新以sqlite的前端方式打开面板又尝试一次，还是成功。过程中工作流也没任何报错，我好迷啊，尝试看了工作流和读取变量的代码，也没有问题啊，所以想问问作者，是不是LeanCloud存在其它问题？如果确实是我操作存在问题，那好叭。

感谢作者的新版前端方案，很好用！

**Comment by hiltay** [comment]
根据你的描述，我从程序角度提供一些解答，供参考排查：

> 但是LeanCloud中并没有新建friend_list和friend_poor

这个时候页面是否能正常展示数据？
> 这个时候我以为是ID和Key填错了，又删库重复操作了两遍结果还是相同

如果`APPID`和`APPKEY`填错，程序是无法运行的，所以应该没有填错

另外，手动切换数据库时，github需要同时更新`STORAGE_TYPE`的值才能生效

**Comment by GC-ZF** [comment]
> 这个时候页面是否能正常展示数据？
是指Leancloud的数据库么？可以访问，但是没新建表。还是指 域名/all ，这个不能访问显示vercel那个错误页面
我刚看了下Leancloud，这几天的数据确实都在Leancloud。应该是当时有什么操作不当吧
