### ISSUE TITLE
关于将此插件内置于 Stellar 和 Volantis 主题的想法和方案探讨

### ISSUE THREAD

**Issue by xaoxuu** [Rock-Candy-Tea/hexo-circle-of-friends#69]
这是一个很棒的插件，所以我想集成到主题中，作为一个无需配置开箱即用的功能。现有的模式可能做不到开箱即用（因为需要后端配置），我想能不能做成像 [#issues-api](https://github.com/xaoxuu/issues-api) 一样把数据存储到仓库中（这个项目也是受冰老师启发和指导），前端直接通过GItHub API 拉取存放于仓库的数据。

这样主题使用者就不需要任何后端配置就可以直接使用此功能了。

JSON存放到仓库中有些功能不方便支持，但我认为那也不是必要的，只要保留最近100条按发布时间倒序排序就可以了。（核心诉求：基础功能+无后端）

**Comment by hiltay** [comment]
目前的核心逻辑（爬虫/rss解析/读取数据）都是通过后端实现的，完全无后端可能难以实现。
但是，可以考虑将读取数据功能改为前端实现，
比如将后端运行在github action上，让前端直接读取数据库，以省略后端api的部署（只实现基础功能，这样可以减少绝大多数配置）。

**Comment by hiltay** [comment]
目前有一个开发群，欢迎一起进群讨论:)
我的qq：904108079

**Comment by hiltay** [comment]
5.0.4版本已添加极简模式，应该可以满足需求。
see：https://github.com/Rock-Candy-Tea/hexo-circle-of-friends/commit/60d5dc0322423d5ff7c51e525dab0f0df2f1a876

**Comment by xaoxuu** [comment]
👍
