### ISSUE TITLE
LINK 未设置导致的程序不再正常尝试截取友链问题

### ISSUE THREAD

**Issue by cworld1** [Rock-Candy-Tea/hexo-circle-of-friends#79]
所有文档里的步骤我都看得懂而且应该都没有错，但最后抓取的时候，还是出了问题…

起因：发现文档步骤结束后，api查询不到任何内容
中途：发现 Github Actions 里的日志显示抓取 0 篇内容
结果：正常网页是通过模板网页从json文件中获取的，也就是发送了 GET 请求，最终得到的页面内元素。目测是因为抓取的是源网页文件而没有运行上边的JS代码，而从而彻底丢失其中的主要内容。

![image](https://user-images.githubusercontent.com/37377181/208164449-5a0d1144-31da-4e4b-832e-f793de44c889.png)

思考过后的方案：
- 将友链内容改为 JSON 格式，友链页面改为二次 GET 请求（第一次获取内容模板，第二次为逐个填充友链内容）从 JSON 中获取。但一来要写 JS 获取，二来损失了加载速度。
- 直接弃用抓取法，改用手工录入友链。缺点是非常麻烦

两种方法都很难受😭

**Comment by cworld1** [comment]
使用方案1解决了绝大部分问题，友链能被读取到，但仍然生成不了，麻烦帮忙看下（代码量过大看糊涂了

![image](https://user-images.githubusercontent.com/37377181/208186629-6e68dbf7-bf2b-4af8-a642-7fc061e4122c.png)

**Comment by hiltay** [comment]
配置文件是什么样子的？

**Comment by cworld1** [comment]
已经解决问题，发现 `LINK` 配置项必须被配置，无论被用到与否。麻烦调整配置逻辑。

**Comment by hiltay** [comment]
是的，`LINK`作为起始参数必须传入。（在文件注释里也有写）

**Comment by cworld1** [comment]
但这样是不太符合部分用户需求的（

**Comment by hiltay** [comment]
谢谢反馈，后续更新会注意到这点

**Comment by hiltay** [comment]
[5.0.8](https://github.com/Rock-Candy-Tea/hexo-circle-of-friends/releases/tag/5.0.8)更新，在配置项友链存在的情况下可不配置`LINK`

**Comment by cworld1** [comment]
好的，感谢更新，辛苦了
