### ISSUE TITLE
默认加载20条是可以修改的吗？

### ISSUE THREAD

**Issue by cajunlei** [Rock-Candy-Tea/hexo-circle-of-friends#82]
我样式设置的分3列显示，默认20条导致很尴尬，仅找到点击加载更多显示的条数。

**Comment by hiltay** [comment]
初始加载的文章数量是20，目前版本不能修改。
谢谢反馈，后续版本会做成可配置项。

**Comment by hiltay** [comment]
[新版](https://fcircle-doc.yyyzyyyz.cn/#/frontenddeploy?id=%e6%96%b9%e6%a1%88%ef%bc%9ayyyz)已添加该功能。
