### ISSUE TITLE
前端控制面板登录密码问题

### ISSUE THREAD

**Issue by Phbeats** [Rock-Candy-Tea/hexo-circle-of-friends#84]
一、 问题描述
第一次登录，即使什么也不输入也能成功登录
在此情况之下，退出登录，输入密码，重复操作，现在我莫名其妙有三个密码！
二、我的"解决方案"
心里想着等大佬更新，但是好像还需要很久，于是想着把控制面板的“设置”给它隐藏掉，遗憾的是自身能力不足，无法在爬取之后进行dom操作，使用DOMContentLoaded也仅在有缓存的情况下有用，第一次进入网站，“设置”还是会出现，所以我解决不了这个问题
三、我的需求（球球）
1. 能否通过配置文件的形式，配置是否显示前端控制面板的“设置”（如果无法大更新情况下的权宜之计）。
2. 当然，如果可以的话，要是可以直接在配置文件里面设置密码就好了，在博客里有一个登录接口而且是能用空密码登录的接口是真的很恐怖的┭┮﹏┭┮。
3. 如果实在都不行，能告诉我如何重置密码吗，我真的不想要三个密码（尤其是空密码）

四、致谢
大佬辛苦了！

**Comment by hiltay** [comment]
一：
![image](https://user-images.githubusercontent.com/41409512/211485708-8b869ab4-c4ff-4aa4-b57a-da4e85be7bb7.png)
如果想重置密码，可清空数据库`auth`和`secret`表。根据描述，我猜部署方式为vercel/sqlite，并且是在短时间内连续输入几次密码登录，造成多个密码都可以登录的"假象"，实际密码仍然为一个。
三、
1.收到建议，后续更新会考虑添加。
2.考虑到有github仓库的存在（fork仓库为公开仓库），直接在配置文件填写密码等同于暴露密码，因此不可行。
3.如上。

**Comment by hiltay** [comment]
请参考[如何修改前端管理面板密码？](https://fcircle-doc.yyyzyyyz.cn/#/problems?id=%e5%a6%82%e4%bd%95%e4%bf%ae%e6%94%b9%e5%89%8d%e7%ab%af%e7%ae%a1%e7%90%86%e9%9d%a2%e6%9d%bf%e5%af%86%e7%a0%81%ef%bc%9f)
