### ISSUE TITLE
求助...

### ISSUE THREAD

**Issue by ning0818** [Rock-Candy-Tea/hexo-circle-of-friends#86]
![image](https://user-images.githubusercontent.com/117955401/212627606-dff34cb6-a57f-45cb-b01e-3144e69f04c5.png)

![image](https://user-images.githubusercontent.com/117955401/212627407-04fa8f91-32cd-4c66-8b50-e339bc470166.png)

![image](https://user-images.githubusercontent.com/117955401/212627775-adb9227a-2076-4668-a1cb-d55075b616d9.png)

![image](https://user-images.githubusercontent.com/117955401/212627875-6bee298a-934b-4c25-9831-a6e2466495aa.png)

![image](https://user-images.githubusercontent.com/117955401/212627931-9f11f861-3f4b-4f42-9a0c-2323124a300e.png)

![image](https://user-images.githubusercontent.com/117955401/212627989-71f05fe0-35cb-4389-aa15-279b0069b89e.png)

**Comment by hiltay** [comment]
1、如果没有获取到文则不会生成`data.db`，缺失该文件就会导致后续的上传出问题。
2、可能是`secret`配置问题
3、检查`secret`权限是否没给够；

**Comment by ning0818** [comment]
> 1、如果没有获取到文章则不会生成，缺失该文件就会导致后续的上传出问题； 2、可能是配置问题； 3、检查权限是否没给够；`data.db``secret``secret`

secret是啥？

**Comment by hiltay** [comment]
请参考[issues87](https://github.com/Rock-Candy-Tea/hexo-circle-of-friends/issues/87)

**Comment by ning0818** [comment]
![image](https://user-images.githubusercontent.com/117955401/217451282-85773cf6-de01-4e60-aeae-6d97a0a8a205.png)

**Comment by hiltay** [comment]
> 1、如果没有获取到文章则不会生成`data.db`，缺失该文件就会导致后续的上传出问题； 2、可能是`secret`配置问题； 3、检查`secret`权限是否没给够；

按照这个检查了吗？

**Comment by ning0818** [comment]
> > 1、如果没有获取到文章则不会生成`data.db`，缺失该文件就会导致后续的上传出问题； 2、可能是`secret`配置问题； 3、检查`secret`权限是否没给够；
> 
> 按照这个检查了吗？

![image](https://user-images.githubusercontent.com/117955401/217757411-2e686568-418f-4ad7-abe2-b7875790d366.png)

**Comment by hiltay** [comment]
没有获取到文章。看看主题是否支持吧。

**Comment by ning0818** [comment]
> 没有获取到文章。看看主题是否支持吧。或者使用通用方案

应该是支持的.我的主题是volantis，https://dusays.com也是volantis，但是https://dusays.com/fcircle/

**Comment by ning0818** [comment]
我去

![image](https://user-images.githubusercontent.com/117955401/217969999-ec84858c-4f4b-47e8-9ca2-4dd77b12d32a.png)
