### ISSUE TITLE
请求更新文档

### ISSUE THREAD

**Issue by GC-ZF** [Rock-Candy-Tea/hexo-circle-of-friends#87]
最近好像蛮多人问这个的，群里和issue里都有，https://github.com/Rock-Candy-Tea/hexo-circle-of-friends/issues/86
<img height="900px"
 src="https://user-images.githubusercontent.com/94956933/213414853-29ff3968-48ff-47d8-b511-19be86a437ac.png">

主要原因是GitHub最近改版了好多，仓库默认没有读权限了，所以sqlite部署的话就push不上去

<img height="600px"
 src="https://user-images.githubusercontent.com/94956933/213415302-a463cb57-b4e3-4560-9b95-448c8a1f2a3c.png">

backenddeploy.md大概更改如下：

xxx前面的内容xxx

然后点击仓库的`setting-->Actions-->General-->勾选Read and write permissions-->Save`
![image](https://user-images.githubusercontent.com/94956933/213417834-bfaa96c2-070f-43e2-a939-2a05e74f3e1d.png)

前往[vercel官网](https://vercel.com/)，直接用github创建账号并用手机号绑定。

xxx后面的内容xxx

**Comment by hiltay** [comment]
感谢反馈。经过检查，新建仓库仍然拥有读写权限，但是fork的仓库只有读权限没有写权限，导致无法上传文件至仓库。
文档已经更新。

**Comment by GC-ZF** [comment]
> 感谢反馈。经过检查，新建仓库仍然拥有读写权限，但是fork的仓库只有读权限没有写权限，导致无法上传文件至仓库。 文档已经更新。

我刚拿俩号都试了新建确实没读权限，可能和个人设置有关系吧，不过影响不大，文档能用就行了

**Comment by hiltay** [comment]
> > 感谢反馈。经过检查，新建仓库仍然拥有读写权限，但是fork的仓库只有读权限没有写权限，导致无法上传文件至仓库。 文档已经更新。
> 
> 我刚拿俩号都试了新建确实没读权限，可能和个人设置有关系吧，不过影响不大，文档能用就行了

今天创建仓库的时候看了一下，确实是已经默认只读权限了:(
