### ISSUE TITLE
butterfly主题开启懒加载后图片无法加载出来

### ISSUE THREAD

**Issue by wayne0926** [Rock-Candy-Tea/hexo-circle-of-friends#9]
# 开启懒加载后
![image](https://user-images.githubusercontent.com/63389859/118983734-5320b580-b9af-11eb-8536-1b4bacc7af6c.png)
# 关闭懒加载后
![image](https://user-images.githubusercontent.com/63389859/118983893-82cfbd80-b9af-11eb-85b6-bb3112a588c7.png)

**Comment by 2X-ercha** [comment]
并不是后端的问题，前端请用最新方案（写成div的那版）或者采用店长的npm方案

若无其他问题该issue将被关闭
