### ISSUE TITLE
成功过几次后突然抓取失败{"message": "start error"}

### ISSUE THREAD

**Issue by lizilong1993** [Rock-Candy-Tea/hexo-circle-of-friends#94]
按照教程已经修改了simple mode 和友链地址，之前还是可以成功抓取的，不知道啥时候就一直抓取失败了

![image](https://user-images.githubusercontent.com/25758122/225838929-bea8b66c-4b5f-4466-8097-d611c00b26a3.png)

![image](https://user-images.githubusercontent.com/25758122/225838850-105e0c96-90b9-442d-9cc0-1523b5f5a673.png)

请问各位大佬，我这是什么地方配置错了吗？求指点，非常感谢！

**Comment by hiltay** [comment]
![1679296048423](https://user-images.githubusercontent.com/41409512/226270125-7fe54422-1b5c-4e38-918b-2a7e391f1ec6.png)

**Comment by lizilong1993** [comment]
> ![1679296048423](https://user-images.githubusercontent.com/41409512/226270125-7fe54422-1b5c-4e38-918b-2a7e391f1ec6.png)
感谢大佬回复！
但是我修改了这里还是出现了同样的问题🤣
![image](https://user-images.githubusercontent.com/25758122/226311188-0241c061-d43a-4e3a-a0b9-bf5f3f1b14a0.png)
![image](https://user-images.githubusercontent.com/25758122/226311314-7d139b51-6258-4d56-b88b-a26465df094a.png)
![image](https://user-images.githubusercontent.com/25758122/226311425-ea16c384-c56c-4d45-bfc5-bb462f4b32d4.png)

**Comment by lizilong1993** [comment]
> 主题不支持？文档里有排查方法
感谢回复，根据官方文档排查错误，发现是我的友链页不满足抓取要求，因为我安装了某个插件导致我的友链样式class名改了。
