### ISSUE TITLE
爬不到，没有上传到leancloud

### ISSUE THREAD

**Issue by xiaohao8** [Rock-Candy-Tea/hexo-circle-of-friends#97]
仓库也没有数据文件，用的是fluid主题，权限也给了

**Comment by hiltay** [comment]
缺少配置项，按照文档操作。

**Comment by xiaohao8** [comment]
文档地址打不开，看的是二猹的

**Comment by xiaohao8** [comment]
![Screenshot_20230409-055215](http://img.202271.xyz:57549/i/2023/04/09/95yf7g.png)
![Screenshot_20230409-055307](http://img.202271.xyz:57549/i/2023/04/09/96gxyc.png)

**Comment by xiaohao8** [comment]
http://img.202271.xyz:57549/application/list.php
这是图片

**Comment by hiltay** [comment]
https://github.com/hiltay/hexo-circle-of-friends-doc
